- hosts: localhost

  vars:
    source_key: "./ssh_keys/id_local"
    dest_key: "{{ lookup('env', 'HOME') }}/.local/share/ssh/id_local"
    github_key: "./ssh_keys/id_github"
    github_dest_key: "{{ lookup('env', 'HOME') }}/.local/share/ssh/id_github"
    gitlab_key: "./ssh_keys/id_gitlab"
    gitlab_dest_key: "{{ lookup('env', 'HOME') }}/.local/share/ssh/id_gitlab"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/share/npm-global/bin:{{ lookup('env', 'PATH') }}"

  pre_tasks:
    - name: Update Apt
      when: ansible_facts['os_family'] == "Debian"      
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags: ["install", "core"]
    - name: Update Homebrew
      when: ansible_facts['os_family'] == "Darwin"
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

  tasks:
    - name: Include SSH
      ansible.builtin.include_tasks: tasks/ssh.yml
    - name: Include Core
      ansible.builtin.include_tasks: tasks/core.yml
    - name: Include Node
      ansible.builtin.include_tasks: tasks/node.yml
