- hosts: localhost

  connection: local

  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_facts['os_family'] }}.yml"

  vars:
    source_key: "./ssh_keys/id_local"
    dest_key: "{{ lookup('env', 'HOME') }}/.local/share/ssh/id_local"
    github_key: "./ssh_keys/id_github"
    github_dest_key: "{{ lookup('env', 'HOME') }}/.local/share/ssh/id_github"
    gitlab_key: "./ssh_keys/id_gitlab"
    gitlab_dest_key: "{{ lookup('env', 'HOME') }}/.local/share/ssh/id_gitlab"
    personal: "{{ lookup('env', 'HOME') }}/personal"

  environment:
    N_PREFIX: "{{ lookup('env', 'HOME') }}/.local/share/n"
    PATH: "{{ lookup('env', 'HOME') }}/.local/share/npm-global/bin:{{ lookup('env', 'HOME') }}/.local/share/n/bin:{{ lookup('env', 'PATH') }}"

  pre_tasks:
    - name: Update Apt
      when: ansible_facts['os_family'] == "Debian"
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags: ["always"]
    - name: Update Homebrew
      when: ansible_facts['os_family'] == "Darwin"
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      tags: ["always"]

  tasks:
    - name: Include SSH
      ansible.builtin.include_tasks:
        file: tasks/ssh.yml
        apply:
          tags: ["always", "ssh", "node", "zsh", "neovim", "emacs", "dotfiles", "misc", "fonts"]
    - name: Include Core
      ansible.builtin.include_tasks:
        file: tasks/core.yml
        apply:
          tags: ["always", "node", "zsh", "neovim", "emacs", "dotfiles", "misc"]
    - name: Include Dotfiles
      ansible.builtin.include_tasks:
        file: tasks/dotfiles.yml
        apply:
          tags: ["always", "dotfiles", "neovim", "emacs", "fonts"]
    - name: Include Node
      ansible.builtin.include_tasks:
        file: tasks/node.yml
        apply:
          tags: ["always", "node"]
    - name: Include Python
      ansible.builtin.include_tasks:
        file: tasks/python.yml
        apply:
          tags: ["always", "python"]
    - name: Include Ruby
      ansible.builtin.include_tasks:
        file: tasks/ruby.yml
        apply:
          tags: ["always", "ruby"]
    - name: Include Zsh
      ansible.builtin.include_tasks:
        file: tasks/zsh.yml
        apply:
          tags: ["always", "zsh"]
    - name: Include Neovim
      ansible.builtin.include_tasks:
        file: tasks/neovim.yml
        apply:
          tags: ["always", "neovim"]
    - name: Include Emacs
      ansible.builtin.include_tasks:
        file: tasks/emacs.yml
        apply:
          tags: ["always", "emacs"]
    - name: Include Kitty
      ansible.builtin.include_tasks:
        file: tasks/kitty.yml
        apply:
          tags: ["always", "kitty"]
    - name: Include Misc
      ansible.builtin.include_tasks:
        file: tasks/misc.yml
        apply:
          tags: ["always", "misc"]
    - name: Include Fonts
      ansible.builtin.include_tasks:
        file: tasks/fonts.yml
        apply:
          tags: ["always", "fonts", "dotfiles", "emacs"]
