- name: Install stow
  apt: name=stow
  tags: &tags_for_dotfiles_tasks ["install", "dotfiles", "stow"]
- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:rgnns/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/personal/dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags: *tags_for_dotfiles_tasks
- name: Stow dotfiles
  shell: cd ~/personal/dotfiles && ./scripts/linux.sh
  tags: *tags_for_dotfiles_tasks
