- name: Apt install Stow
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt: name=stow

- name: Brew install Stow
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: stow
    state: present

- name: Check dotfiles
  stat:
    path: "{{ lookup('env', 'HOME') }}/personal/dotfiles"
  register: dotfiles_dir

- name: Create tmp SSH config
  when: not dotfiles_dir.stat.exists
  shell: echo "Host github.com\n\tHostName github.com\n\tIdentityFile ~/.local/share/ssh/id_github" > ~/.ssh/config

- name: Clone dotfiles
  when: not dotfiles_dir.stat.exists
  ansible.builtin.git:
    repo: "git@github.com:rgnns/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/personal/dotfiles"
    update: yes
    accept_hostkey: yes
    version: main

- name: Remove tmp SSH config
  when: not dotfiles_dir.stat.exists
  shell: rm ~/.ssh/config

- name: Stow linux dotfiles
  when: ansible_facts['os_family'] == "Debian"
  shell: cd ~/personal/dotfiles && ./scripts/linux.sh

- name: Stow darwin dotfiles
  when: ansible_facts['os_family'] == "Darwin"
  shell: cd ~/personal/dotfiles && ./scripts/darwin.sh

