- name: Apt install Stow
  when: ansible_facts['os_family'] == "Debian"
  apt: name=stow

- name: Brew install Stow
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: stow
    state: present

# TODO: check if already exists
- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:rgnns/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/personal/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Stow linux dotfiles
  when: ansible_facts['os_family'] == "Debian"
  shell: cd ~/personal/dotfiles && ./scripts/linux.sh

- name: Stow darwin dotfiles
  when: ansible_facts['os_family'] == "Darwin"
  shell: cd ~/personal/dotfiles && ./scripts/darwin.sh

