- name: Check Emacs config directory
  ansible.builtin.shell: ls $HOME/.config/emacs
  register: emacs_dir_contents

- name: Apt install Emacs
  when: ansible_facts['os_family'] == "Debian"
  apt: name=emacs

- name: Brew install Emacs
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: rgnns/core/emacs
    state: present

- name: Pull Emacs configuration
  when: emacs_dir_contents.stdout.find('init.el') == -1
  ansible.builtin.git:
    repo: "git@github.com:rgnns/emacs-config.git"
    dest: "{{ lookup('env', 'HOME') }}/.config/emacs"
    update: yes
    accept_hostkey: yes
    version: main

- name: Build Emacs configuration
  when: emacs_dir_contents.stdout.find('init.el') == -1
  shell: cd ~/.config/emacs && make bootstrap-borg && make bootstrap

