- name: Install packages
  become: true
  apt:
    name:
      - aria2
      - bat
      - fzf
      - gcc
      - ghc
      - gimp
      - git-lfs
      - gnupg
      - graphviz
      - haskell-language-server
      - httpie
      - imagemagick
      - inotify-tools
      - jq
      - just
      - ledger
      - openjdk-11-jdk1
      - ripgrep
      - shellcheck
      - shfmt
      - sqlite
      - tldr
      - tmux
      - xclip
  tags:
    - install
    - misc
