- name: Check Pyenv installation
  stat:
    path: "{{ lookup('env', 'HOME') }}/.pyenv"
  register: pyenv_dir

- name: Install Pyenv
  when: not pyenv_dir.stat.exists
  ansible.builtin.git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ lookup('env', 'HOME') }}/.pyenv"

- name: Build Pyenv
  when: not pyenv_dir.stat.exists
  shell: cd ~/.pyenv && src/configure && make -C src
