- name: Check Pyenv installation
  shell: ls $HOME/.pyenv
  register: pyenv_dir_contents

- name: Install Pyenv
  when: pyenv_dir_contents.stdout.find('Makefile') == -1
  ansible.builtin.git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ lookup('env', 'HOME') }}/.pyenv"

- name: Build Pyenv
  when: pyenv_dir_contents.stdout.find('Makefile') == -1
  shell: cd ~/.pyenv && src/configure && make -C src
