- name: Ensure .ssh directory exists
  file:
    dest: "{{ local_dest_key | dirname }}"
    mode: 0700
    state: directory

- name: Install ssh local key
  copy:
    src: "{{ local_key }}"
    dest: "{{ local_dest_key }}"
    mode: 0600

- name: Install ssh local public key
  copy:
    src: "{{ local_key }}.pub"
    dest: "{{ local_dest_key }}.pub"
    mode: 0644

- name: Install ssh github key
  copy:
    src: "{{ github_key }}"
    dest: "{{ github_dest_key }}"
    mode: 0600

- name: Install ssh github public key
  copy:
    src: "{{ github_key }}.pub"
    dest: "{{ github_dest_key }}.pub"
    mode: 0644

- name: Install ssh gitlab key
  copy:
    src: "{{ gitlab_key }}"
    dest: "{{ gitlab_dest_key }}"
    mode: 0600

- name: Install ssh gitlab public key
  copy:
    src: "{{ gitlab_key }}.pub"
    dest: "{{ gitlab_dest_key }}.pub"
    mode: 0644

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.local/share/ssh/id_local.pub') }}"
