- name: Install Zsh
  when: ansible_facts['os_family'] == "Debian"
  apt: name=zsh

- name: Install Zsh
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew:
    name: ["zsh", "zsh-completions"]
    state: present

# TODO: `which zsh` won't work on macOS
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
